No longer simplify code into attr_reader/writer
This proposal removes support for converting code like
```
def x
  @x
end
```
into `attr_reader :x` (and similar for `attr_writer :x`).

In most contexts the expressions are equivalent, but not always. For example, if you feed the string to `instance_eval`, then
```
instance_eval "def x; @x; end"
```
executes just fine, while
```
parser = RubyParser.new
r2r = Ruby2Ruby.new
instance_eval r2r.process(parser.parse("def x; @x; end"))`
```
will fail with `NoMethodError: undefined method `attr_reader' for main:Object`.

An assumption behind this change is that RubyParser + Ruby2Ruby are intended to 'roundtrip' and result in code that is equivalent for all practical purposes.